### ISSUE TITLE
#

### ISSUE THREAD

**Issue by 2Lost4This** [AerGameChannel/AntiScam-Bot#5]
Error:

npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"anv"} (current: {"os":"linux"."arch":"x64“})
npm ERR! notsup Valid OS: darwin
npm ERR! notsup Valid Arch: anv
npm ERR! notsup Actual OS: linux
npm ERR! notsup Actual Arch: x64  

How i can fix that?

**Comment by AerGameChannel** [comment]
npm install --no-optional

**Comment by 2Lost4This** [comment]
> npm install --no-optional

Still getting the Error, so what can i do?

**Comment by AerGameChannel** [comment]
Try to install discord.js, prettier, husky, pretty-quick, nodemon and fs manually. 

npm install discord.js prettier husky pretty-quick nodemon fs

Or update your npm to latest version. Current version is 8.3.0.

sudo npm install -g npm@8.3.0

**Comment by 2Lost4This** [comment]
> Try to install discord.js, prettier, husky, pretty-quick, nodemon and fs manually.
> 
> npm install discord.js prettier husky pretty-quick nodemon fs
> 
> Or update your npm to latest version. Current version is 8.3.0.
> 
> sudo npm install -g npm@8.3.0

If i try to install manually, im getting the first error. 
Npm is updated

![image](https://user-images.githubusercontent.com/91763324/146078088-32c22d37-e05b-4c21-a38c-bbe3b85a26bf.png)

**Comment by AerGameChannel** [comment]
Actually i have no idea why npm can't install those packages for you. I tested it on my Ubuntu 20.04 and everything works fine, it installs all the packages.
![image](https://user-images.githubusercontent.com/63594377/146008780-433e2366-5eaf-4d7e-8ab6-f25facf5e649.png)
I found a post on stackoverflow and someone told to force npm to install packages. Maybe it will work for you.

npm install -f

**Comment by 2Lost4This** [comment]
> Actually i have no idea why npm can't install those packages for you. I tested it on my Ubuntu 20.04 and everything works fine, it installs all the packages. ![image](https://user-images.githubusercontent.com/63594377/146008780-433e2366-5eaf-4d7e-8ab6-f25facf5e649.png) I found a post on stackoverflow and someone told to force npm to install packages. Maybe it will work for you.
> 
> npm install -f

Okey i fixed it with that, thanks but now i got the problem i cant start the bot, idk why

**Comment by AerGameChannel** [comment]
Does it give any output?

**Comment by 2Lost4This** [comment]
> Does it give any output?

![image](https://user-images.githubusercontent.com/91763324/146089348-52053f13-fd29-4b3c-9112-eb4bc1af8681.png)

**Comment by 2Lost4This** [comment]
![image](https://user-images.githubusercontent.com/91763324/146089434-c6ee12de-fac0-4035-999f-0393d639e0a1.png)

i think its because that:
![image](https://user-images.githubusercontent.com/91763324/146089547-bffc6fa6-dbb9-4755-80a9-499b2d904ade.png)

Do you have dc i think its easier to write there

**Comment by AerGameChannel** [comment]
Aer#4332

**Comment by AerGameChannel** [comment]
Solved. The incorrect nodejs version was installed.
